services:
  - type: web
    name: gastos-pessoais-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run migrate && node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        fromDatabase:
          name: gastos-pessoais-db
          property: connectionString

databases:
  - name: gastos-pessoais-db
    databaseName: gastos_pessoais
    user: gastos_user
    plan: free
